# Generated by Django 4.1.1 on 2022-10-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0001_initial'),
        ('game', '0002_game_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='profile_users.profile'),
            preserve_default=False,
        ),
    ]