# Generated by Django 4.1.1 on 2022-10-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0001_initial'),
        ('game', '0003_remove_game_owner_id_game_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='profile_users.profile'),
        ),
    ]
