# Generated by Django 4.1.1 on 2022-10-11 08:12

from django.db import migrations, models
import exam_prep_GamesPlay.validators


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[exam_prep_GamesPlay.validators.validate_max_level], verbose_name='Max Level'),
        ),
    ]
